title: UnityBase
subtitle: "Full-Stack JavaScript framework for Enterprise"
description: "UnityBase - fast, simple & powerful full stack JavaScript framework for a BIG applications."
author: UnityBase team
language: en
timezone: UTC
url: https://unitybase.info
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: ub
deploy:
  type: 
  repo: 

favicon: /favicon.ico

disqus_shortname: UnityBase
google_analytics: 
fb_admins: 
algolia:
twitter: unitybase
github: unitybasejs
facebook: platformUnityBase
rss: /atom.xml
