<!-- Tweet button -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="https://unitybase.info/" data-text="UnityBase - Full stack JavaScript framework for Enterprise" data-hashtags="{{config.twitter}}">Tweet</a>
<!-- Twitter follow button -->
<a href="https://twitter.com/{{config.twitter}}" class="twitter-follow-button" data-show-count="false">Follow @{{config.twitter}}</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
